package fr.uga.l3miage.pc.enums;

public enum StrategieEnum {
    ADAPTATIF,
    ALEATOIRE,
    DONNANT_DONNANT,
    DONNANT_DONNANT_SOUPCONNEUX,
    DONNANT_DONNANT_ALEATOIRE,
    DONNANT_POUR_DEUX_DONNANTS,
    DONNANT_POUR_DEUX_DONNANTS_ALEATOIRE,
    GRADUEL,
    PACIFICATEUR_NAIF,
    PAVLOV,
    PAVLOV_ALEATOIRE,
    RANCUNIER,
    RANCUNIER_DOUX,
    SONDEUR_NAIF,
    SONDEUR_REPENTANT,
    TOUJOURS_COOPERER,
    TOUJOURS_TRAHIR,
    VRAI_PACIFICATEUR;
}